version: 1
identity:
  hostname: pi
  username: darren
  password: $6$FhcddHFVZ7ABA4Gi$5KozDPX/AqVc.G7KrbEE0HMbrb1hu0DJHP0/ARdPfHxvNo9Qo.5YVhtexCm17VFJUoVCmWNK3j.q63hS8d7K61
ssh:
  install-server: yes
  authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC55o4RGp1/7k6F0j2TgjTDxiyT6uFXZx+mPQUC2fAhloNhs657tKpDnTu09VE/iXai17R80W9BsGciabE+0S7/j3HS+Rv3ZcMm7gbCf16TpG75AcUrhTziI8wActnOqERVPH28pYp3UfgmFxfkOF4JHvnGpqR5gHNKyHAIqlroAdryS1qV4oMLFEUH5YzDYtavdVW7QSdwogynjyswvMso7nGwbUjDq05Cx+tnyn9I6iP2vsOxHjuFQcaExgXL/8A3W3bRoUv0ng/iiKbvLA5mFEGTz/W8wNFnjxb24Rz1df9R5btyBzsHK5fjoyUiZZuCjxwgGjJKfqxUBpQutfQrF3+DVBfPR/WUxsnt+a2ykrsSBkoYKin6MJsPr4U82dtQg1GDuFsPoinEyYTgz5SGD4QeAmbbPO+8YyWe/jHufpAc7xx+jgGRbFjY+KnPyIHI9umDtyY4VpCOW+90NmvW2mi1Zqf7fSl4HsJ2kFo2dq9nP4nGK9hmk+3ZxZam9cc= darren@Darrens-MBP.lan"
  allow-pw: no
package_update: true
package_upgrade: true
runcmd:
  - [sudo, snap, install, docker]
  - [
      wget,
      -q,
      -O,
      /home/ubuntu/compose.yaml,
      https://gist.githubusercontent.com/da1rren/8a8943d8f7dbbff35da58a6be9c6af57/raw/07adf81f571aa39b54311ec332b99c308b514b8d/compose.yaml,
    ]
  - [sudo, docker-compose, -f, /home/ubuntu/compose.yaml, up, -d]
