name: build-plant-watering-agent

on:
  push:
    branches:
      - 'main'

jobs:
  build-plant-watering-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: home/Home.Plant.Watering
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build HomeLab Agent Image'
        run: |
          docker buildx ls
          docker buildx build --platform linux/arm64/v8 -t ghcr.io/${{github.actor}}/plant-watering-agent:latest --push .
