name: build-plant-watering-server

on:
  push:
    branches:
      - 'main'

jobs:
  build-plant-watering-server:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: home/Home.Plant.Watering  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        id:   gitversion

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build HomeLab Server Image'
        run: |
          docker build -f Home.Plant.Watering.Ui/Dockerfile . \
          --tag ghcr.io/${{github.actor}}/plant-watering-server:latest \
          --tag ghcr.io/${{github.actor}}/plant-watering-server:${{ steps.gitversion.outputs.fullSemVer }} 

          docker push ghcr.io/${{github.actor}}/plant-watering-server:latest