name: build-plant-watering-agent

on:
  push:
    branches:
      - 'main'

jobs:
  build-plant-watering-agent:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: home/Home.Plant.Watering
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Home.Plant.Watering.Agent/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{github.actor}}/plant-watering-agent:latest

