name: build-plant-watering-server

on:
  push:
    branches:
      - 'main'

jobs:
  build-plant-watering-server:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: home/Home.Plant.Watering  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        id:   gitversion

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build HomeLab Server Image'
        run: |
          docker build -f Home.Plant.Watering.Ui/Dockerfile . \
          --tag ghcr.io/${{github.actor}}/plant-watering-server:latest \
          --tag ghcr.io/${{github.actor}}/plant-watering-server:${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }} 

          docker push ghcr.io/${{github.actor}}/plant-watering-server:latest
          docker push ghcr.io/${{github.actor}}/plant-watering-server:${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config container set --name home-ui \
            --resource-group home-ui \
            --docker-custom-image-name ghcr.io/${{github.actor}}/plant-watering-server:${{ steps.gitversion.outputs.semVer }}-${{ steps.gitversion.outputs.shortSha }} \
            --docker-registry-server-url https://ghcr.io/